'use client'

import { useEffect, useState } from 'react'
import type { TocItem } from '@/lib/docs'

/**
 * Right-hand "On this page" rail. Highlights the heading currently in view
 * via IntersectionObserver. Headings carry ids generated by rehype-slug at
 * bake time, matching the `id`s stored in each chapter's `toc`.
 */
export default function DocsToc({ items }: { items: TocItem[] }) {
  const [activeId, setActiveId] = useState<string>('')

  useEffect(() => {
    if (items.length === 0) return

    const headings = items
      .map((i) => document.getElementById(i.id))
      .filter((el): el is HTMLElement => el !== null)

    if (headings.length === 0) return

    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top)
        if (visible[0]) setActiveId(visible[0].target.id)
      },
      { rootMargin: '-80px 0px -70% 0px', threshold: 0 }
    )

    headings.forEach((h) => observer.observe(h))
    return () => observer.disconnect()
  }, [items])

  if (items.length === 0) return null

  return (
    <nav className="hidden xl:block sticky top-24 self-start w-52 shrink-0">
      <div className="font-mono text-xs text-[#e8ff47] tracking-widest uppercase mb-4">
        On this page
      </div>
      <ul className="flex flex-col gap-1 border-l border-white/8">
        {items.map((item) => {
          const active = item.id === activeId
          return (
            <li key={item.id}>
              <a
                href={`#${item.id}`}
                className={`block text-sm leading-snug py-1 transition-colors -ml-px border-l-2 ${
                  item.depth === 3 ? 'pl-6' : 'pl-3'
                } ${
                  active
                    ? 'border-[#e8ff47] text-[#e8ff47]'
                    : 'border-transparent text-[#71717a] hover:text-[#a1a1aa]'
                }`}
              >
                {item.text}
              </a>
            </li>
          )
        })}
      </ul>
    </nav>
  )
}
