'use client'

import { useEffect, useState } from 'react'
import type { TocItem } from '@/lib/docs'

/**
 * Right-hand "On this page" rail. Highlights the heading currently in view
 * via IntersectionObserver. Headings carry ids generated by rehype-slug at
 * bake time, matching the `id`s stored in each chapter's `toc`.
 */
export default function DocsToc({
  items,
  editHref,
}: {
  items: TocItem[]
  editHref?: string
}) {
  const [activeId, setActiveId] = useState<string>('')
  const [feedback, setFeedback] = useState<'yes' | 'no' | null>(null)

  useEffect(() => {
    if (items.length === 0) return

    const headings = items
      .map((i) => document.getElementById(i.id))
      .filter((el): el is HTMLElement => el !== null)

    if (headings.length === 0) return

    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top)
        if (visible[0]) setActiveId(visible[0].target.id)
      },
      { rootMargin: '-80px 0px -70% 0px', threshold: 0 }
    )

    headings.forEach((h) => observer.observe(h))
    return () => observer.disconnect()
  }, [items])

  return (
    <nav className="hidden xl:block sticky top-[76px] self-start w-[220px] shrink-0 max-h-[calc(100vh-96px)] overflow-y-auto py-6 pl-1.5 pr-2">
      {items.length > 0 && (
        <>
          <div className="text-[12px] font-bold tracking-[0.07em] uppercase text-[#a3a3a3] dark:text-[#374151] mb-2.5">
            On this page
          </div>
          <ul className="flex flex-col">
            {items.map((item) => {
              const active = item.id === activeId
              return (
                <li key={item.id}>
                  <a
                    href={`#${item.id}`}
                    className={[
                      'block text-[15px] leading-[1.4] py-0.5 pl-2.5 border-l transition-colors',
                      item.depth === 3 ? 'ml-2.5 text-[14px]' : '',
                      active
                        ? 'text-[#7c3aed] border-[#7c3aed] font-medium'
                        : 'text-[#a3a3a3] dark:text-[#374151] border-black/[0.08] dark:border-white/[0.07] hover:text-[#18181b] dark:hover:text-[#edf0fa]',
                    ].join(' ')}
                  >
                    {item.text}
                  </a>
                </li>
              )
            })}
          </ul>
          <hr className="my-3 border-black/[0.08] dark:border-white/[0.07]" />
        </>
      )}

      <div className="flex items-center justify-between gap-2">
        {editHref && (
          <a
            href={editHref}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1 text-[13px] text-[#a3a3a3] dark:text-[#374151] hover:text-[#7c3aed] transition-colors"
          >
            <svg width="11" height="11" viewBox="0 0 12 12" fill="none">
              <path d="M7 2l3 3M2 7l5-5 3 3-5 5H2V7z" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            Edit page
          </a>
        )}
        <div className="flex items-center gap-1 ml-auto">
          {(['yes', 'no'] as const).map((v) => (
            <button
              key={v}
              onClick={() => setFeedback(v)}
              title={v === 'yes' ? 'Helpful' : 'Not helpful'}
              className={[
                'w-7 h-7 flex items-center justify-center rounded text-[14px] transition-colors',
                feedback === v ? 'bg-[rgba(91,33,182,0.1)]' : 'hover:bg-black/[0.04] dark:hover:bg-white/[0.06]',
              ].join(' ')}
            >
              {v === 'yes' ? '👍' : '👎'}
            </button>
          ))}
        </div>
      </div>
      {feedback && (
        <p className="text-[12.5px] text-[#a3a3a3] dark:text-[#374151] mt-1.5">
          {feedback === 'yes' ? 'Thanks!' : 'Thanks — noted.'}
        </p>
      )}
    </nav>
  )
}
